--- #YAML:1.0
name:                Language-GolfScript
version:             0.04
abstract:            Perl implementation of GolfScript 
license:             perl
author:              
    - Marty O'Brien <mob@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Slurp:                   9999
    Filter::Simple:                0.79
    Math::BigInt:                  1.87
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
