--- #YAML:1.0
name:               Language-GolfScript
version:            0.01
abstract:           Perl implementation of GolfScript 
author:
    - Marty O'Brien <mob@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filter::Simple:  0.79
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
